# Generated by Django 4.2.5 on 2023-09-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundcontribution',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
