# Generated by Django 4.2.5 on 2023-10-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDonate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='image',
        ),
    ]
